### ISSUE TITLE
https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.slim.min.js is down

### ISSUE THREAD

**Issue by rezad1393** [Doradx/CNKI-PDF-RIS-Helper#1]
https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.slim.min.js
Web server is down Error code 521
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=cdn.bootcdn.net) for more information.
2022-09-08 06:49:26 UTC

**Comment by Doradx** [comment]
Is OK for me.
Maybe you should check your internet.

**Comment by rezad1393** [comment]
right now it is up again.
