### ISSUE TITLE
导出RIS文件年份信息错误。

### ISSUE THREAD

**Issue by kennyzjc1994** [Doradx/CNKI-PDF-RIS-Helper#2]
有一个问题。在我访问这个界面并导出结果后。发现年份不对。正常的应该是2022，但是结果里面是2023。 链接：
https://kns.cnki.net/kcms2/article/abstract?v=3HpZxZdrsp0fFHgMgH_PhaONUaRJpAhfjs2RLQqhRJWnFn_qe1mkrgExvspkqSK-Y7TTYnKCJB0qg94oI2UnadKxPESrShCzGoIPiizogLQPpWd9t4XxoJlrJwzwVjOW&uniplatform=NZKPT&language=gb

公平竞争审查制度能否促进企业创新？——基于规制行政垄断的视角

**Comment by Doradx** [comment]
你好，导出过程不会修改数据。
据考证，所提案例，首发于2022，实际刊发于2023，请以知网实际导出为准。
感谢反馈
